package com.ecannetwork.dto.tech;

import com.ecannetwork.core.module.db.dto.DtoSupport;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * EcanDomainvalue generated by hbm2java
 */
public class EcanDomainvalue extends DtoSupport implements java.io.Serializable
{

	private String id;
	private int indexsequnce;
	private String domainlabel;
	private String domainId;
	private String value;
	private String domainlevel;
	private String isDelete;

	public EcanDomainvalue()
	{
	}

	public EcanDomainvalue(String id, int indexsequnce, String domainlabel,
			String domainId, String value)
	{
		this.id = id;
		this.indexsequnce = indexsequnce;
		this.domainlabel = domainlabel;
		this.domainId = domainId;
		this.value = value;
	}

	public EcanDomainvalue(String id, int indexsequnce, String domainlabel,
			String domainId, String value, String domainlevel, String isDelete)
	{
		this.id = id;
		this.indexsequnce = indexsequnce;
		this.domainlabel = domainlabel;
		this.domainId = domainId;
		this.value = value;
		this.domainlevel = domainlevel;
		this.isDelete = isDelete;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public int getIndexsequnce()
	{
		return this.indexsequnce;
	}

	public void setIndexsequnce(int indexsequnce)
	{
		this.indexsequnce = indexsequnce;
	}

	public String getDomainlabel()
	{
		return this.domainlabel;
	}

	public void setDomainlabel(String domainlabel)
	{
		this.domainlabel = domainlabel;
	}

	public String getDomainId()
	{
		return this.domainId;
	}

	public void setDomainId(String domainId)
	{
		this.domainId = domainId;
	}

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	public String getDomainlevel()
	{
		return this.domainlevel;
	}

	public void setDomainlevel(String domainlevel)
	{
		this.domainlevel = domainlevel;
	}

	public String getIsDelete()
	{
		return this.isDelete;
	}

	public void setIsDelete(String isDelete)
	{
		this.isDelete = isDelete;
	}

}
