package com.ecannetwork.dto.tech;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwServicecost generated by hbm2java
 */
public class MwServicecost extends DtoSupport implements java.io.Serializable
{

	private String id;
	private String userid;
	private String content;
	private String tableid;
	private Integer projectid;
	private Integer a1;
	private Integer a2;
	private String a3;
	private String a4;
	private Date createTime;

	public MwServicecost()
	{
	}

	public MwServicecost(String userid, String content, String tableid,
			Integer projectid, Integer a1, Integer a2, String a3, String a4,
			Date createTime)
	{
		this.userid = userid;
		this.content = content;
		this.tableid = tableid;
		this.projectid = projectid;
		this.a1 = a1;
		this.a2 = a2;
		this.a3 = a3;
		this.a4 = a4;
		this.createTime = createTime;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getUserid()
	{
		return this.userid;
	}

	public void setUserid(String userid)
	{
		this.userid = userid;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getTableid()
	{
		return this.tableid;
	}

	public void setTableid(String tableid)
	{
		this.tableid = tableid;
	}

	public Integer getProjectid()
	{
		return this.projectid;
	}

	public void setProjectid(Integer projectid)
	{
		this.projectid = projectid;
	}

	public Integer getA1()
	{
		return this.a1;
	}

	public void setA1(Integer a1)
	{
		this.a1 = a1;
	}

	public Integer getA2()
	{
		return this.a2;
	}

	public void setA2(Integer a2)
	{
		this.a2 = a2;
	}

	public String getA3()
	{
		return this.a3;
	}

	public void setA3(String a3)
	{
		this.a3 = a3;
	}

	public String getA4()
	{
		return this.a4;
	}

	public void setA4(String a4)
	{
		this.a4 = a4;
	}

	public Date getCreateTime()
	{
		return this.createTime;
	}

	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

}
