package com.ecannetwork.dto.tech;

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwVotecourse generated by hbm2java
 */
public class MwSktcourse extends DtoSupport implements java.io.Serializable {
  
  private String id;
  
  private String CName;
  
  private String CCode;
  
  private Integer CCourseid;
  
  private String CCourse;
  
  private Date dtCreateTime;
  
  private Integer islocked;
  
  private String CContent;
  
  public MwSktcourse() {
  }
  
  public MwSktcourse(String CName, String CCode, Integer CCourseid, String CCourse,
      Date dtCreateTime, Integer islocked, String CContent) {
    this.CName = CName;
    this.CCode = CCode;
    this.CCourseid = CCourseid;
    this.CCourse = CCourse;
    this.dtCreateTime = dtCreateTime;
    this.islocked = islocked;
    this.CContent = CContent;
  }
  
  public String getId() {
    return this.id;// DtoSupport.java中该方法为抽象方法，类型为String，但是该表字段为int，修改映射文件
  }
  
  public void setId(String id) {
    this.id = id;
  }
  
  public String getCName() {
    return this.CName;
  }
  
  public void setCName(String CName) {
    this.CName = CName;
  }
  
  public String getCCode() {
    return this.CCode;
  }
  
  public void setCCode(String CCode) {
    this.CCode = CCode;
  }
  
  public Integer getCCourseid() {
    return this.CCourseid;
  }
  
  public void setCCourseid(Integer CCourseid) {
    this.CCourseid = CCourseid;
  }
  
  public String getCCourse() {
    return this.CCourse;
  }
  
  public void setCCourse(String CCourse) {
    this.CCourse = CCourse;
  }
  
  public Date getdtCreateTime() {
    return this.dtCreateTime;
  }
  
  public void setdtCreateTime(Date dtCreateTime) {
    this.dtCreateTime = dtCreateTime;
  }
  
  public Integer getislocked() {
    return this.islocked;
  }
  
  public void setislocked(Integer islocked) {
    this.islocked = islocked;
  }
  
  public String getCContent() {
    return this.CContent;
  }
  
  public void setCContent(String CContent) {
    this.CContent = CContent;
  }
  
}