package com.ecannetwork.dto.tech;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwSktresultitem generated by hbm2java
 */
public class MwSktresultitem extends DtoSupport implements java.io.Serializable
{

	private String id;
	private Integer cid;
	private Integer sort;
	private String CName;
	private Integer CType;
	private String CContent;
	private Date createTime;
	private Integer islock;
	private Integer chapterid;
	private String uid;
	private String userName;

	public MwSktresultitem()
	{
	}

	public MwSktresultitem(Integer cid, Integer sort, String CName,
			Integer CType, String CContent, Date createTime, Integer islock,
			Integer chapterid, String uid, String userName)
	{
		this.cid = cid;
		this.sort = sort;
		this.CName = CName;
		this.CType = CType;
		this.CContent = CContent;
		this.createTime = createTime;
		this.islock = islock;
		this.chapterid = chapterid;
		this.uid = uid;
		this.userName = userName;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public Integer getCid()
	{
		return this.cid;
	}

	public void setCid(Integer cid)
	{
		this.cid = cid;
	}

	public Integer getSort()
	{
		return this.sort;
	}

	public void setSort(Integer sort)
	{
		this.sort = sort;
	}

	public String getCName()
	{
		return this.CName;
	}

	public void setCName(String CName)
	{
		this.CName = CName;
	}

	public Integer getCType()
	{
		return this.CType;
	}

	public void setCType(Integer CType)
	{
		this.CType = CType;
	}

	public String getCContent()
	{
		return this.CContent;
	}

	public void setCContent(String CContent)
	{
		this.CContent = CContent;
	}

	public Date getCreateTime()
	{
		return this.createTime;
	}

	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

	public Integer getIslock()
	{
		return this.islock;
	}

	public void setIslock(Integer islock)
	{
		this.islock = islock;
	}

	public Integer getChapterid()
	{
		return this.chapterid;
	}

	public void setChapterid(Integer chapterid)
	{
		this.chapterid = chapterid;
	}

	public String getUid()
	{
		return this.uid;
	}

	public void setUid(String uid)
	{
		this.uid = uid;
	}

	public String getUserName()
	{
		return this.userName;
	}

	public void setUserName(String userName)
	{
		this.userName = userName;
	}

}
