package com.ecannetwork.dto.tech;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwTestdriverpg generated by hbm2java
 */
public class MwTestdriverpg extends DtoSupport implements java.io.Serializable
{

	private String id;
	private Integer cid;
	private Integer fid;
	private Integer fvalue;
	private String fstring;
	private String CCourseid;
	private String CCourse;
	private String CTeacherid;
	private String CTeacher;
	private String chexiId;
	private String chexi;
	private Integer changdiId;
	private String changdi;
	private String student;
	private String studentId;
	private Date createTime;

	public MwTestdriverpg()
	{
	}

	public MwTestdriverpg(Integer cid, Integer fid, Integer fvalue,
			String fstring, String CCourseid, String CCourse,
			String CTeacherid, String CTeacher, String chexiId, String chexi,
			Integer changdiId, String changdi, String student,
			String studentId, Date createTime)
	{
		this.cid = cid;
		this.fid = fid;
		this.fvalue = fvalue;
		this.fstring = fstring;
		this.CCourseid = CCourseid;
		this.CCourse = CCourse;
		this.CTeacherid = CTeacherid;
		this.CTeacher = CTeacher;
		this.chexiId = chexiId;
		this.chexi = chexi;
		this.changdiId = changdiId;
		this.changdi = changdi;
		this.student = student;
		this.studentId = studentId;
		this.createTime = createTime;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public Integer getCid()
	{
		return this.cid;
	}

	public void setCid(Integer cid)
	{
		this.cid = cid;
	}

	public Integer getFid()
	{
		return this.fid;
	}

	public void setFid(Integer fid)
	{
		this.fid = fid;
	}

	public Integer getFvalue()
	{
		return this.fvalue;
	}

	public void setFvalue(Integer fvalue)
	{
		this.fvalue = fvalue;
	}

	public String getFstring()
	{
		return this.fstring;
	}

	public void setFstring(String fstring)
	{
		this.fstring = fstring;
	}

	public String getCCourseid()
	{
		return this.CCourseid;
	}

	public void setCCourseid(String CCourseid)
	{
		this.CCourseid = CCourseid;
	}

	public String getCCourse()
	{
		return this.CCourse;
	}

	public void setCCourse(String CCourse)
	{
		this.CCourse = CCourse;
	}

	public String getCTeacherid()
	{
		return this.CTeacherid;
	}

	public void setCTeacherid(String CTeacherid)
	{
		this.CTeacherid = CTeacherid;
	}

	public String getCTeacher()
	{
		return this.CTeacher;
	}

	public void setCTeacher(String CTeacher)
	{
		this.CTeacher = CTeacher;
	}

	public String getChexiId()
	{
		return this.chexiId;
	}

	public void setChexiId(String chexiId)
	{
		this.chexiId = chexiId;
	}

	public String getChexi()
	{
		return this.chexi;
	}

	public void setChexi(String chexi)
	{
		this.chexi = chexi;
	}

	public Integer getChangdiId()
	{
		return this.changdiId;
	}

	public void setChangdiId(Integer changdiId)
	{
		this.changdiId = changdiId;
	}

	public String getChangdi()
	{
		return this.changdi;
	}

	public void setChangdi(String changdi)
	{
		this.changdi = changdi;
	}

	public String getStudent()
	{
		return this.student;
	}

	public void setStudent(String student)
	{
		this.student = student;
	}

	public String getStudentId()
	{
		return this.studentId;
	}

	public void setStudentId(String studentId)
	{
		this.studentId = studentId;
	}

	public Date getCreateTime()
	{
		return this.createTime;
	}

	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

}
