package com.ecannetwork.dto.tech;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwTestdrivertime generated by hbm2java
 */
public class MwTestdrivertime extends DtoSupport implements java.io.Serializable
{

	private String id;
	private Integer cid;
	private String CCourseid;
	private String CCourse;
	private String CTeacherid;
	private String CTeacher;
	private Date startTime;
	private Date endTime;
	private String chexiId;
	private String chexi;
	private Integer changdiId;
	private String changdi;
	private String student;
	private String studentId;
	private Double useTime;
	private Date createTime;

	public MwTestdrivertime()
	{
	}

	public MwTestdrivertime(Integer cid, String CCourseid, String CCourse,
			String CTeacherid, String CTeacher, Date startTime, Date endTime,
			String chexiId, String chexi, Integer changdiId, String changdi,
			String student, String studentId, Double useTime, Date createTime)
	{
		this.cid = cid;
		this.CCourseid = CCourseid;
		this.CCourse = CCourse;
		this.CTeacherid = CTeacherid;
		this.CTeacher = CTeacher;
		this.startTime = startTime;
		this.endTime = endTime;
		this.chexiId = chexiId;
		this.chexi = chexi;
		this.changdiId = changdiId;
		this.changdi = changdi;
		this.student = student;
		this.studentId = studentId;
		this.useTime = useTime;
		this.createTime = createTime;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public Integer getCid()
	{
		return this.cid;
	}

	public void setCid(Integer cid)
	{
		this.cid = cid;
	}

	public String getCCourseid()
	{
		return this.CCourseid;
	}

	public void setCCourseid(String CCourseid)
	{
		this.CCourseid = CCourseid;
	}

	public String getCCourse()
	{
		return this.CCourse;
	}

	public void setCCourse(String CCourse)
	{
		this.CCourse = CCourse;
	}

	public String getCTeacherid()
	{
		return this.CTeacherid;
	}

	public void setCTeacherid(String CTeacherid)
	{
		this.CTeacherid = CTeacherid;
	}

	public String getCTeacher()
	{
		return this.CTeacher;
	}

	public void setCTeacher(String CTeacher)
	{
		this.CTeacher = CTeacher;
	}

	public Date getStartTime()
	{
		return this.startTime;
	}

	public void setStartTime(Date startTime)
	{
		this.startTime = startTime;
	}

	public Date getEndTime()
	{
		return this.endTime;
	}

	public void setEndTime(Date endTime)
	{
		this.endTime = endTime;
	}

	public String getChexiId()
	{
		return this.chexiId;
	}

	public void setChexiId(String chexiId)
	{
		this.chexiId = chexiId;
	}

	public String getChexi()
	{
		return this.chexi;
	}

	public void setChexi(String chexi)
	{
		this.chexi = chexi;
	}

	public Integer getChangdiId()
	{
		return this.changdiId;
	}

	public void setChangdiId(Integer changdiId)
	{
		this.changdiId = changdiId;
	}

	public String getChangdi()
	{
		return this.changdi;
	}

	public void setChangdi(String changdi)
	{
		this.changdi = changdi;
	}

	public String getStudent()
	{
		return this.student;
	}

	public void setStudent(String student)
	{
		this.student = student;
	}

	public String getStudentId()
	{
		return this.studentId;
	}

	public void setStudentId(String studentId)
	{
		this.studentId = studentId;
	}

	public Double getUseTime()
	{
		return this.useTime;
	}

	public void setUseTime(Double useTime)
	{
		this.useTime = useTime;
	}

	public Date getCreateTime()
	{
		return this.createTime;
	}

	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

}
