package com.ecannetwork.dto.tech;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwTestdriver generated by hbm2java
 */
public class MwTestdriver extends DtoSupport implements java.io.Serializable
{

	private String id;
	private String CName;
	private String CCode;
	private String CCourseid;
	private String CCourse;
	private String CTeacherid;
	private String CTeacher;
	private Date createTime;
	private String students;
	private String chexi;
	private String changdi;
	private String pgfield;

	public MwTestdriver()
	{
	}

	public MwTestdriver(String CName, String CCode, String CCourseid,
			String CCourse, String CTeacherid, String CTeacher,
			Date createTime, String students, String chexi, String changdi,
			String pgfield)
	{
		this.CName = CName;
		this.CCode = CCode;
		this.CCourseid = CCourseid;
		this.CCourse = CCourse;
		this.CTeacherid = CTeacherid;
		this.CTeacher = CTeacher;
		this.createTime = createTime;
		this.students = students;
		this.chexi = chexi;
		this.changdi = changdi;
		this.pgfield = pgfield;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getCName()
	{
		return this.CName;
	}

	public void setCName(String CName)
	{
		this.CName = CName;
	}

	public String getCCode()
	{
		return this.CCode;
	}

	public void setCCode(String CCode)
	{
		this.CCode = CCode;
	}

	public String getCCourseid()
	{
		return this.CCourseid;
	}

	public void setCCourseid(String CCourseid)
	{
		this.CCourseid = CCourseid;
	}

	public String getCCourse()
	{
		return this.CCourse;
	}

	public void setCCourse(String CCourse)
	{
		this.CCourse = CCourse;
	}

	public String getCTeacherid()
	{
		return this.CTeacherid;
	}

	public void setCTeacherid(String CTeacherid)
	{
		this.CTeacherid = CTeacherid;
	}

	public String getCTeacher()
	{
		return this.CTeacher;
	}

	public void setCTeacher(String CTeacher)
	{
		this.CTeacher = CTeacher;
	}

	public Date getCreateTime()
	{
		return this.createTime;
	}

	public void setCreateTime(Date createTime)
	{
		this.createTime = createTime;
	}

	public String getStudents()
	{
		return this.students;
	}

	public void setStudents(String students)
	{
		this.students = students;
	}

	public String getChexi()
	{
		return this.chexi;
	}

	public void setChexi(String chexi)
	{
		this.chexi = chexi;
	}

	public String getChangdi()
	{
		return this.changdi;
	}

	public void setChangdi(String changdi)
	{
		this.changdi = changdi;
	}

	public String getPgfield()
	{
		return this.pgfield;
	}

	public void setPgfield(String pgfield)
	{
		this.pgfield = pgfield;
	}

}
