package com.ecannetwork.dto.tech;

import com.ecannetwork.core.module.db.dto.DtoSupport;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * MwTestdriverfield generated by hbm2java
 */
public class MwTestdriverfield extends DtoSupport implements java.io.Serializable
{

	private String id;
	private String CName;
	private Integer parentId;
	private String colPath;
	private Integer orderby;
	private Integer isUse;
	private String remark;

	public MwTestdriverfield()
	{
	}

	public MwTestdriverfield(String CName, Integer parentId, String colPath,
			Integer orderby, Integer isUse, String remark)
	{
		this.CName = CName;
		this.parentId = parentId;
		this.colPath = colPath;
		this.orderby = orderby;
		this.isUse = isUse;
		this.remark = remark;
	}

	public String getId()
	{
		return this.id;
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public String getCName()
	{
		return this.CName;
	}

	public void setCName(String CName)
	{
		this.CName = CName;
	}

	public Integer getParentId()
	{
		return this.parentId;
	}

	public void setParentId(Integer parentId)
	{
		this.parentId = parentId;
	}

	public String getColPath()
	{
		return this.colPath;
	}

	public void setColPath(String colPath)
	{
		this.colPath = colPath;
	}

	public Integer getOrderby()
	{
		return this.orderby;
	}

	public void setOrderby(Integer orderby)
	{
		this.orderby = orderby;
	}

	public Integer getIsUse()
	{
		return this.isUse;
	}

	public void setIsUse(Integer isUse)
	{
		this.isUse = isUse;
	}

	public String getRemark()
	{
		return this.remark;
	}

	public void setRemark(String remark)
	{
		this.remark = remark;
	}

}
