package com.ecannetwork.dto.tech;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwVoteresult generated by hbm2java
 */
public class MwVoteresult extends DtoSupport implements java.io.Serializable
{

	private String id;
	private Integer NKeyId;
	private Integer NSubId;
	private String CReuslt;
	private Integer NTestId;
	private Integer NVoteId;
	private Integer NSysId;
	private Date dtDate;
	private Integer NLogicPageId;
	private String CLic;
	private String CIp;
	private Integer IsTemp;

	public MwVoteresult()
	{
	}

	public MwVoteresult(Integer NKeyId, Integer NSubId, String CReuslt,
			Integer NTestId, Integer NVoteId, Integer NSysId, Date dtDate,
			Integer NLogicPageId, String CLic, String CIp)
	{
		this.NKeyId = NKeyId;
		this.NSubId = NSubId;
		this.CReuslt = CReuslt;
		this.NTestId = NTestId;
		this.NVoteId = NVoteId;
		this.NSysId = NSysId;
		this.dtDate = dtDate;
		this.NLogicPageId = NLogicPageId;
		this.CLic = CLic;
		this.CIp = CIp;
	}

	public String getId()
	{
		return this.id;// DtoSupport.java中该方法为抽象方法，类型为String，但是该表字段为int，修改映射文件
	}

	public void setId(String id)
	{
		this.id = id;
	}

	public Integer getNKeyId()
	{
		return this.NKeyId;
	}

	public void setNKeyId(Integer NKeyId)
	{
		this.NKeyId = NKeyId;
	}

	public Integer getNSubId()
	{
		return this.NSubId;
	}

	public void setNSubId(Integer NSubId)
	{
		this.NSubId = NSubId;
	}

	public String getCReuslt()
	{
		return this.CReuslt;
	}

	public void setCReuslt(String CReuslt)
	{
		this.CReuslt = CReuslt;
	}

	public Integer getNTestId()
	{
		return this.NTestId;
	}

	public void setNTestId(Integer NTestId)
	{
		this.NTestId = NTestId;
	}

	public Integer getNVoteId()
	{
		return this.NVoteId;
	}

	public void setNVoteId(Integer NVoteId)
	{
		this.NVoteId = NVoteId;
	}

	public Integer getNSysId()
	{
		return this.NSysId;
	}

	public void setNSysId(Integer NSysId)
	{
		this.NSysId = NSysId;
	}

	public Date getDtDate()
	{
		return this.dtDate;
	}

	public void setDtDate(Date dtDate)
	{
		this.dtDate = dtDate;
	}

	public Integer getNLogicPageId()
	{
		return this.NLogicPageId;
	}

	public void setNLogicPageId(Integer NLogicPageId)
	{
		this.NLogicPageId = NLogicPageId;
	}

	public String getCLic()
	{
		return this.CLic;
	}

	public void setCLic(String CLic)
	{
		this.CLic = CLic;
	}

	public String getCIp()
	{
		return this.CIp;
	}

	public void setCIp(String CIp)
	{
		this.CIp = CIp;
	}

	public Integer getIsTemp()
	{
		return IsTemp;
	}

	public void setIsTemp(Integer isTemp)
	{
		IsTemp = isTemp;
	}
	
}
