package com.ecannetwork.dto.tech;

import com.ecannetwork.core.module.db.dto.DtoSupport;

// Generated Jan 23, 2016 11:15:36 PM by Hibernate Tools 3.4.0.CR1

/**
 * MwVoteunit generated by hbm2java
 */
public class MwVoteunit extends DtoSupport implements java.io.Serializable
{

	private String id;
	private Integer NSysId;
	private String CSubTitle;
	private Integer NOrderId;
	private Integer NNeed;
	private Integer parentid;
	private String colpath;
	private Integer NType;

	public MwVoteunit()
	{
	}

	public MwVoteunit(Integer NSysId, String CSubTitle, Integer NOrderId,
			Integer NNeed, Integer parentid, String colpath, Integer NType)
	{
		this.NSysId = NSysId;
		this.CSubTitle = CSubTitle;
		this.NOrderId = NOrderId;
		this.NNeed = NNeed;
		this.parentid = parentid;
		this.colpath = colpath;
		this.NType = NType;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getNSysId()
	{
		return this.NSysId;
	}

	public void setNSysId(Integer NSysId)
	{
		this.NSysId = NSysId;
	}

	public String getCSubTitle()
	{
		return this.CSubTitle;
	}

	public void setCSubTitle(String CSubTitle)
	{
		this.CSubTitle = CSubTitle;
	}

	public Integer getNOrderId()
	{
		return this.NOrderId;
	}

	public void setNOrderId(Integer NOrderId)
	{
		this.NOrderId = NOrderId;
	}

	public Integer getNNeed()
	{
		return this.NNeed;
	}

	public void setNNeed(Integer NNeed)
	{
		this.NNeed = NNeed;
	}

	public Integer getParentid()
	{
		return this.parentid;
	}

	public void setParentid(Integer parentid)
	{
		this.parentid = parentid;
	}

	public String getColpath()
	{
		return this.colpath;
	}

	public void setColpath(String colpath)
	{
		this.colpath = colpath;
	}

	public Integer getNType()
	{
		return this.NType;
	}

	public void setNType(Integer NType)
	{
		this.NType = NType;
	}

}
