package com.ecannetwork.dto.tech;

import java.util.Date;

import com.ecannetwork.core.module.db.dto.DtoSupport;

/**
 * MwVotecourse generated by hbm2java
 */
public class SqPassatB8 extends DtoSupport implements java.io.Serializable {
  
  private String id;
  
  private String usertype;
  
  private String type;
  
  private Date startTime;
  
  private String carType;
  
  private String bigItem;
  
  private String item;
  
  private Double score;
  
  public SqPassatB8() {
  }
  
  public String getId() {
    return this.id;// DtoSupport.java中该方法为抽象方法，类型为String，但是该表字段为int，修改映射文件
  }
  
  public void setId(String id) {
    this.id = id;
  }
  
  public SqPassatB8(String id, String usertype, String type, Date startTime, String carType,
      String bigItem, String item, Double score) {
    super();
    this.id = id;
    this.usertype = usertype;
    this.type = type;
    this.startTime = startTime;
    this.carType = carType;
    this.bigItem = bigItem;
    this.item = item;
    this.score = score;
  }
  
  public String getUsertype() {
    return usertype;
  }
  
  public void setUsertype(String usertype) {
    this.usertype = usertype;
  }
  
  public String getType() {
    return type;
  }
  
  public void setType(String type) {
    this.type = type;
  }
  
  public Date getStartTime() {
    return startTime;
  }
  
  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }
  
  public String getCarType() {
    return carType;
  }
  
  public void setCarType(String carType) {
    this.carType = carType;
  }
  
  public String getBigItem() {
    return bigItem;
  }
  
  public void setBigItem(String bigItem) {
    this.bigItem = bigItem;
  }
  
  public String getItem() {
    return item;
  }
  
  public void setItem(String item) {
    this.item = item;
  }
  
  public Double getScore() {
    return score;
  }
  
  public void setScore(Double score) {
    this.score = score;
  }
  
}